// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// CertificateSigningRequestExpansion is an autogenerated mock type for the CertificateSigningRequestExpansion type
type CertificateSigningRequestExpansion struct {
	mock.Mock
}

type CertificateSigningRequestExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *CertificateSigningRequestExpansion) EXPECT() *CertificateSigningRequestExpansion_Expecter {
	return &CertificateSigningRequestExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewCertificateSigningRequestExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewCertificateSigningRequestExpansion creates a new instance of CertificateSigningRequestExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCertificateSigningRequestExpansion(t mockConstructorTestingTNewCertificateSigningRequestExpansion) *CertificateSigningRequestExpansion {
	mock := &CertificateSigningRequestExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
