// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1 "k8s.io/client-go/kubernetes/typed/certificates/v1"
)

// CertificatesV1Interface is an autogenerated mock type for the CertificatesV1Interface type
type CertificatesV1Interface struct {
	mock.Mock
}

type CertificatesV1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *CertificatesV1Interface) EXPECT() *CertificatesV1Interface_Expecter {
	return &CertificatesV1Interface_Expecter{mock: &_m.Mock}
}

// CertificateSigningRequests provides a mock function with given fields:
func (_m *CertificatesV1Interface) CertificateSigningRequests() v1.CertificateSigningRequestInterface {
	ret := _m.Called()

	var r0 v1.CertificateSigningRequestInterface
	if rf, ok := ret.Get(0).(func() v1.CertificateSigningRequestInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.CertificateSigningRequestInterface)
		}
	}

	return r0
}

// CertificatesV1Interface_CertificateSigningRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateSigningRequests'
type CertificatesV1Interface_CertificateSigningRequests_Call struct {
	*mock.Call
}

// CertificateSigningRequests is a helper method to define mock.On call
func (_e *CertificatesV1Interface_Expecter) CertificateSigningRequests() *CertificatesV1Interface_CertificateSigningRequests_Call {
	return &CertificatesV1Interface_CertificateSigningRequests_Call{Call: _e.mock.On("CertificateSigningRequests")}
}

func (_c *CertificatesV1Interface_CertificateSigningRequests_Call) Run(run func()) *CertificatesV1Interface_CertificateSigningRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CertificatesV1Interface_CertificateSigningRequests_Call) Return(_a0 v1.CertificateSigningRequestInterface) *CertificatesV1Interface_CertificateSigningRequests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertificatesV1Interface_CertificateSigningRequests_Call) RunAndReturn(run func() v1.CertificateSigningRequestInterface) *CertificatesV1Interface_CertificateSigningRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with given fields:
func (_m *CertificatesV1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// CertificatesV1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type CertificatesV1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *CertificatesV1Interface_Expecter) RESTClient() *CertificatesV1Interface_RESTClient_Call {
	return &CertificatesV1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *CertificatesV1Interface_RESTClient_Call) Run(run func()) *CertificatesV1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CertificatesV1Interface_RESTClient_Call) Return(_a0 rest.Interface) *CertificatesV1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertificatesV1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *CertificatesV1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCertificatesV1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCertificatesV1Interface creates a new instance of CertificatesV1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCertificatesV1Interface(t mockConstructorTestingTNewCertificatesV1Interface) *CertificatesV1Interface {
	mock := &CertificatesV1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
