---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Gateway API standard CRDs
  - https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.4.1&timeout=90s
  # NGINX Gateway Fabric CRDs
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.4.1/deploy/crds.yaml
