// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1alpha1 "k8s.io/client-go/kubernetes/typed/authentication/v1alpha1"
)

// AuthenticationV1alpha1Interface is an autogenerated mock type for the AuthenticationV1alpha1Interface type
type AuthenticationV1alpha1Interface struct {
	mock.Mock
}

type AuthenticationV1alpha1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationV1alpha1Interface) EXPECT() *AuthenticationV1alpha1Interface_Expecter {
	return &AuthenticationV1alpha1Interface_Expecter{mock: &_m.Mock}
}

// RESTClient provides a mock function with given fields:
func (_m *AuthenticationV1alpha1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// AuthenticationV1alpha1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type AuthenticationV1alpha1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *AuthenticationV1alpha1Interface_Expecter) RESTClient() *AuthenticationV1alpha1Interface_RESTClient_Call {
	return &AuthenticationV1alpha1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *AuthenticationV1alpha1Interface_RESTClient_Call) Run(run func()) *AuthenticationV1alpha1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticationV1alpha1Interface_RESTClient_Call) Return(_a0 rest.Interface) *AuthenticationV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticationV1alpha1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *AuthenticationV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// SelfSubjectReviews provides a mock function with given fields:
func (_m *AuthenticationV1alpha1Interface) SelfSubjectReviews() v1alpha1.SelfSubjectReviewInterface {
	ret := _m.Called()

	var r0 v1alpha1.SelfSubjectReviewInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.SelfSubjectReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.SelfSubjectReviewInterface)
		}
	}

	return r0
}

// AuthenticationV1alpha1Interface_SelfSubjectReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelfSubjectReviews'
type AuthenticationV1alpha1Interface_SelfSubjectReviews_Call struct {
	*mock.Call
}

// SelfSubjectReviews is a helper method to define mock.On call
func (_e *AuthenticationV1alpha1Interface_Expecter) SelfSubjectReviews() *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call {
	return &AuthenticationV1alpha1Interface_SelfSubjectReviews_Call{Call: _e.mock.On("SelfSubjectReviews")}
}

func (_c *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call) Run(run func()) *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call) Return(_a0 v1alpha1.SelfSubjectReviewInterface) *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call) RunAndReturn(run func() v1alpha1.SelfSubjectReviewInterface) *AuthenticationV1alpha1Interface_SelfSubjectReviews_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAuthenticationV1alpha1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationV1alpha1Interface creates a new instance of AuthenticationV1alpha1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationV1alpha1Interface(t mockConstructorTestingTNewAuthenticationV1alpha1Interface) *AuthenticationV1alpha1Interface {
	mock := &AuthenticationV1alpha1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
