// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1beta1 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"
)

// AuthenticationV1beta1Interface is an autogenerated mock type for the AuthenticationV1beta1Interface type
type AuthenticationV1beta1Interface struct {
	mock.Mock
}

type AuthenticationV1beta1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationV1beta1Interface) EXPECT() *AuthenticationV1beta1Interface_Expecter {
	return &AuthenticationV1beta1Interface_Expecter{mock: &_m.Mock}
}

// RESTClient provides a mock function with given fields:
func (_m *AuthenticationV1beta1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// AuthenticationV1beta1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type AuthenticationV1beta1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *AuthenticationV1beta1Interface_Expecter) RESTClient() *AuthenticationV1beta1Interface_RESTClient_Call {
	return &AuthenticationV1beta1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *AuthenticationV1beta1Interface_RESTClient_Call) Run(run func()) *AuthenticationV1beta1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticationV1beta1Interface_RESTClient_Call) Return(_a0 rest.Interface) *AuthenticationV1beta1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticationV1beta1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *AuthenticationV1beta1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// TokenReviews provides a mock function with given fields:
func (_m *AuthenticationV1beta1Interface) TokenReviews() v1beta1.TokenReviewInterface {
	ret := _m.Called()

	var r0 v1beta1.TokenReviewInterface
	if rf, ok := ret.Get(0).(func() v1beta1.TokenReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.TokenReviewInterface)
		}
	}

	return r0
}

// AuthenticationV1beta1Interface_TokenReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenReviews'
type AuthenticationV1beta1Interface_TokenReviews_Call struct {
	*mock.Call
}

// TokenReviews is a helper method to define mock.On call
func (_e *AuthenticationV1beta1Interface_Expecter) TokenReviews() *AuthenticationV1beta1Interface_TokenReviews_Call {
	return &AuthenticationV1beta1Interface_TokenReviews_Call{Call: _e.mock.On("TokenReviews")}
}

func (_c *AuthenticationV1beta1Interface_TokenReviews_Call) Run(run func()) *AuthenticationV1beta1Interface_TokenReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticationV1beta1Interface_TokenReviews_Call) Return(_a0 v1beta1.TokenReviewInterface) *AuthenticationV1beta1Interface_TokenReviews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticationV1beta1Interface_TokenReviews_Call) RunAndReturn(run func() v1beta1.TokenReviewInterface) *AuthenticationV1beta1Interface_TokenReviews_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAuthenticationV1beta1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationV1beta1Interface creates a new instance of AuthenticationV1beta1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationV1beta1Interface(t mockConstructorTestingTNewAuthenticationV1beta1Interface) *AuthenticationV1beta1Interface {
	mock := &AuthenticationV1beta1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
