comment: false
codecov:
  require_ci_to_pass: true
  branch: main

coverage:
  precision: 2
  round: down
  range: 50...100

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
    changes: false

ignore:
  - "**/*mock/.*"
  - "pkg/client"
  - "**/zz_generated.deepcopy.go"
  - "_docs"
  - "_run"
  - "script"
  - "make"
