---
version: 2
project_name: provider
env:
  - GO111MODULE=on
  - DOCKER_CLI_EXPERIMENTAL="enabled"
  - CGO_ENABLED=1
before:
  hooks:
    - apt update
    - apt install -y pkg-config libudev-dev:amd64 libudev-dev:arm64
builds:
  - id: provider-services-linux-arm64
    binary: provider-services
    main: ./cmd/provider-services
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.aarch64 -Wl,-z,muldefs -lm -lrt -lc -lpthread"
  - id: provider-services-linux-amd64
    binary: provider-services
    main: ./cmd/provider-services
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.x86_64 -Wl,-z,muldefs -lm -lrt -lc -lpthread"
  - id: provider-services-linux-arm64-debug
    binary: provider-services
    main: ./cmd/provider-services
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.aarch64 -Wl,-z,muldefs -lm -lrt -lc -lpthread"
    gcflags:
      - "all=-N -l"
  - id: provider-services-linux-amd64-debug
    binary: provider-services
    main: ./cmd/provider-services
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.x86_64 -Wl,-z,muldefs -lm -lrt -lc -lpthread"
    gcflags:
      - "all=-N -l"
archives:
  - formats:
      - binary
dockers_v2:
  - id: provider-services
    ids:
      - provider-services-linux-amd64
      - provider-services-linux-arm64
    dockerfile: Dockerfile
    images:
      - "{{ .Env.DOCKER_IMAGE }}"
    tags:
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "{{ .ProjectName }}"
      org.opencontainers.image.url: "{{.GitURL}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"
  - id: provider-services-debug
    ids:
      - provider-services-linux-amd64-debug
      - provider-services-linux-arm64-debug
    dockerfile: Dockerfile.debug
    images:
      - "{{ .Env.DOCKER_IMAGE }}"
    tags:
      - latest-debug
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "{{ .ProjectName }}"
      org.opencontainers.image.url: "{{.GitURL}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"
