---
dir: mocks
structname: '{{.InterfaceName}}'
filename: '{{.InterfaceName}}_mock.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/akash-network/provider:
    config:
      dir: mocks/client
    interfaces:
      StatusClient: {}
      Client: {}
  github.com/akash-network/provider/cluster:
    config:
      dir: mocks/cluster
    interfaces:
      Client: {}
      ReadClient: {}
      Cluster: {}
      Service: {}
  github.com/akash-network/provider/cluster/types/v1beta3:
    config:
      dir: mocks/cluster/types
    interfaces:
      HostnameServiceClient: {}
      ReservationGroup: {}
      Reservation: {}
      IDeployment: {}
  github.com/akash-network/provider/cluster/types/v1beta3/clients/ip:
    config:
      dir: mocks/cluster/types/clients/ip
    interfaces:
      Client: {}
  github.com/akash-network/provider/cluster/kube/operators/clients/metallb:
    config:
      dir: mocks/cluster/kube/operators/clients/metallb
    interfaces:
      Client: {}
  github.com/akash-network/provider/manifest:
    config:
      dir: mocks/manifest
    interfaces:
      Client: {}
      StatusClient: {}
