// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	networkingv1 "k8s.io/api/networking/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/networking/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// NetworkPolicyInterface is an autogenerated mock type for the NetworkPolicyInterface type
type NetworkPolicyInterface struct {
	mock.Mock
}

type NetworkPolicyInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkPolicyInterface) EXPECT() *NetworkPolicyInterface_Expecter {
	return &NetworkPolicyInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, networkPolicy, opts
func (_m *NetworkPolicyInterface) Apply(ctx context.Context, networkPolicy *v1.NetworkPolicyApplyConfiguration, opts metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, networkPolicy, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, networkPolicy, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, networkPolicy, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, networkPolicy, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type NetworkPolicyInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - networkPolicy *v1.NetworkPolicyApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *NetworkPolicyInterface_Expecter) Apply(ctx interface{}, networkPolicy interface{}, opts interface{}) *NetworkPolicyInterface_Apply_Call {
	return &NetworkPolicyInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, networkPolicy, opts)}
}

func (_c *NetworkPolicyInterface_Apply_Call) Run(run func(ctx context.Context, networkPolicy *v1.NetworkPolicyApplyConfiguration, opts metav1.ApplyOptions)) *NetworkPolicyInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.NetworkPolicyApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Apply_Call) Return(result *networkingv1.NetworkPolicy, err error) *NetworkPolicyInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *NetworkPolicyInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function with given fields: ctx, networkPolicy, opts
func (_m *NetworkPolicyInterface) ApplyStatus(ctx context.Context, networkPolicy *v1.NetworkPolicyApplyConfiguration, opts metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, networkPolicy, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, networkPolicy, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, networkPolicy, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, networkPolicy, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type NetworkPolicyInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - networkPolicy *v1.NetworkPolicyApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *NetworkPolicyInterface_Expecter) ApplyStatus(ctx interface{}, networkPolicy interface{}, opts interface{}) *NetworkPolicyInterface_ApplyStatus_Call {
	return &NetworkPolicyInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, networkPolicy, opts)}
}

func (_c *NetworkPolicyInterface_ApplyStatus_Call) Run(run func(ctx context.Context, networkPolicy *v1.NetworkPolicyApplyConfiguration, opts metav1.ApplyOptions)) *NetworkPolicyInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.NetworkPolicyApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_ApplyStatus_Call) Return(result *networkingv1.NetworkPolicy, err error) *NetworkPolicyInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *NetworkPolicyInterface_ApplyStatus_Call) RunAndReturn(run func(context.Context, *v1.NetworkPolicyApplyConfiguration, metav1.ApplyOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, networkPolicy, opts
func (_m *NetworkPolicyInterface) Create(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.CreateOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, networkPolicy, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.CreateOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, networkPolicy, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.CreateOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, networkPolicy, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *networkingv1.NetworkPolicy, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, networkPolicy, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NetworkPolicyInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - networkPolicy *networkingv1.NetworkPolicy
//   - opts metav1.CreateOptions
func (_e *NetworkPolicyInterface_Expecter) Create(ctx interface{}, networkPolicy interface{}, opts interface{}) *NetworkPolicyInterface_Create_Call {
	return &NetworkPolicyInterface_Create_Call{Call: _e.mock.On("Create", ctx, networkPolicy, opts)}
}

func (_c *NetworkPolicyInterface_Create_Call) Run(run func(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.CreateOptions)) *NetworkPolicyInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*networkingv1.NetworkPolicy), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Create_Call) Return(_a0 *networkingv1.NetworkPolicy, _a1 error) *NetworkPolicyInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_Create_Call) RunAndReturn(run func(context.Context, *networkingv1.NetworkPolicy, metav1.CreateOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *NetworkPolicyInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NetworkPolicyInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NetworkPolicyInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *NetworkPolicyInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *NetworkPolicyInterface_Delete_Call {
	return &NetworkPolicyInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *NetworkPolicyInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *NetworkPolicyInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Delete_Call) Return(_a0 error) *NetworkPolicyInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NetworkPolicyInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *NetworkPolicyInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *NetworkPolicyInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NetworkPolicyInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type NetworkPolicyInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *NetworkPolicyInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *NetworkPolicyInterface_DeleteCollection_Call {
	return &NetworkPolicyInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *NetworkPolicyInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *NetworkPolicyInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_DeleteCollection_Call) Return(_a0 error) *NetworkPolicyInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NetworkPolicyInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *NetworkPolicyInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *NetworkPolicyInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NetworkPolicyInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *NetworkPolicyInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *NetworkPolicyInterface_Get_Call {
	return &NetworkPolicyInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *NetworkPolicyInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *NetworkPolicyInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Get_Call) Return(_a0 *networkingv1.NetworkPolicy, _a1 error) *NetworkPolicyInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *NetworkPolicyInterface) List(ctx context.Context, opts metav1.ListOptions) (*networkingv1.NetworkPolicyList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *networkingv1.NetworkPolicyList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*networkingv1.NetworkPolicyList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *networkingv1.NetworkPolicyList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicyList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NetworkPolicyInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *NetworkPolicyInterface_Expecter) List(ctx interface{}, opts interface{}) *NetworkPolicyInterface_List_Call {
	return &NetworkPolicyInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *NetworkPolicyInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *NetworkPolicyInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_List_Call) Return(_a0 *networkingv1.NetworkPolicyList, _a1 error) *NetworkPolicyInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*networkingv1.NetworkPolicyList, error)) *NetworkPolicyInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *NetworkPolicyInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*networkingv1.NetworkPolicy, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type NetworkPolicyInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *NetworkPolicyInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *NetworkPolicyInterface_Patch_Call {
	return &NetworkPolicyInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *NetworkPolicyInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *NetworkPolicyInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *NetworkPolicyInterface_Patch_Call) Return(result *networkingv1.NetworkPolicy, err error) *NetworkPolicyInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *NetworkPolicyInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, networkPolicy, opts
func (_m *NetworkPolicyInterface) Update(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, networkPolicy, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, networkPolicy, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, networkPolicy, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, networkPolicy, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NetworkPolicyInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - networkPolicy *networkingv1.NetworkPolicy
//   - opts metav1.UpdateOptions
func (_e *NetworkPolicyInterface_Expecter) Update(ctx interface{}, networkPolicy interface{}, opts interface{}) *NetworkPolicyInterface_Update_Call {
	return &NetworkPolicyInterface_Update_Call{Call: _e.mock.On("Update", ctx, networkPolicy, opts)}
}

func (_c *NetworkPolicyInterface_Update_Call) Run(run func(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.UpdateOptions)) *NetworkPolicyInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*networkingv1.NetworkPolicy), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Update_Call) Return(_a0 *networkingv1.NetworkPolicy, _a1 error) *NetworkPolicyInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_Update_Call) RunAndReturn(run func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, networkPolicy, opts
func (_m *NetworkPolicyInterface) UpdateStatus(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error) {
	ret := _m.Called(ctx, networkPolicy, opts)

	var r0 *networkingv1.NetworkPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error)); ok {
		return rf(ctx, networkPolicy, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) *networkingv1.NetworkPolicy); ok {
		r0 = rf(ctx, networkPolicy, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkingv1.NetworkPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, networkPolicy, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type NetworkPolicyInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - networkPolicy *networkingv1.NetworkPolicy
//   - opts metav1.UpdateOptions
func (_e *NetworkPolicyInterface_Expecter) UpdateStatus(ctx interface{}, networkPolicy interface{}, opts interface{}) *NetworkPolicyInterface_UpdateStatus_Call {
	return &NetworkPolicyInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, networkPolicy, opts)}
}

func (_c *NetworkPolicyInterface_UpdateStatus_Call) Run(run func(ctx context.Context, networkPolicy *networkingv1.NetworkPolicy, opts metav1.UpdateOptions)) *NetworkPolicyInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*networkingv1.NetworkPolicy), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_UpdateStatus_Call) Return(_a0 *networkingv1.NetworkPolicy, _a1 error) *NetworkPolicyInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *networkingv1.NetworkPolicy, metav1.UpdateOptions) (*networkingv1.NetworkPolicy, error)) *NetworkPolicyInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *NetworkPolicyInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkPolicyInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type NetworkPolicyInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *NetworkPolicyInterface_Expecter) Watch(ctx interface{}, opts interface{}) *NetworkPolicyInterface_Watch_Call {
	return &NetworkPolicyInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *NetworkPolicyInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *NetworkPolicyInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *NetworkPolicyInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *NetworkPolicyInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkPolicyInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *NetworkPolicyInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewNetworkPolicyInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewNetworkPolicyInterface creates a new instance of NetworkPolicyInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNetworkPolicyInterface(t mockConstructorTestingTNewNetworkPolicyInterface) *NetworkPolicyInterface {
	mock := &NetworkPolicyInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
