/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2beta2

import (
	context "context"

	akashnetworkv2beta2 "github.com/akash-network/provider/pkg/apis/akash.network/v2beta2"
	applyconfigurationakashnetworkv2beta2 "github.com/akash-network/provider/pkg/client/applyconfiguration/akash.network/v2beta2"
	scheme "github.com/akash-network/provider/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InventoryRequestsGetter has a method to return a InventoryRequestInterface.
// A group's client should implement this interface.
type InventoryRequestsGetter interface {
	InventoryRequests() InventoryRequestInterface
}

// InventoryRequestInterface has methods to work with InventoryRequest resources.
type InventoryRequestInterface interface {
	Create(ctx context.Context, inventoryRequest *akashnetworkv2beta2.InventoryRequest, opts v1.CreateOptions) (*akashnetworkv2beta2.InventoryRequest, error)
	Update(ctx context.Context, inventoryRequest *akashnetworkv2beta2.InventoryRequest, opts v1.UpdateOptions) (*akashnetworkv2beta2.InventoryRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inventoryRequest *akashnetworkv2beta2.InventoryRequest, opts v1.UpdateOptions) (*akashnetworkv2beta2.InventoryRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*akashnetworkv2beta2.InventoryRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*akashnetworkv2beta2.InventoryRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *akashnetworkv2beta2.InventoryRequest, err error)
	Apply(ctx context.Context, inventoryRequest *applyconfigurationakashnetworkv2beta2.InventoryRequestApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta2.InventoryRequest, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inventoryRequest *applyconfigurationakashnetworkv2beta2.InventoryRequestApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta2.InventoryRequest, err error)
	InventoryRequestExpansion
}

// inventoryRequests implements InventoryRequestInterface
type inventoryRequests struct {
	*gentype.ClientWithListAndApply[*akashnetworkv2beta2.InventoryRequest, *akashnetworkv2beta2.InventoryRequestList, *applyconfigurationakashnetworkv2beta2.InventoryRequestApplyConfiguration]
}

// newInventoryRequests returns a InventoryRequests
func newInventoryRequests(c *AkashV2beta2Client) *inventoryRequests {
	return &inventoryRequests{
		gentype.NewClientWithListAndApply[*akashnetworkv2beta2.InventoryRequest, *akashnetworkv2beta2.InventoryRequestList, *applyconfigurationakashnetworkv2beta2.InventoryRequestApplyConfiguration](
			"inventoryrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *akashnetworkv2beta2.InventoryRequest { return &akashnetworkv2beta2.InventoryRequest{} },
			func() *akashnetworkv2beta2.InventoryRequestList { return &akashnetworkv2beta2.InventoryRequestList{} },
		),
	}
}
