package tee

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"time"
)

// MockProvider returns synthetic attestation reports for local development
// and testing without TEE hardware. Activated when ATTESTATION_MOCK=true.
//
// The mock report is deterministic given the same report_data: it embeds
// the nonce in a recognizable structure so tests can verify the nonce echo
// (invariant #5) without real hardware.
//
// NEVER use in production. The mock report has no cryptographic validity.
type MockProvider struct {
	TEE string // "snp" or "tdx" — controls the reported TEE type
}

var _ Provider = (*MockProvider)(nil)

func (m *MockProvider) Name() string {
	if m.TEE != "" {
		return m.TEE
	}
	return NameSNP
}

func (m *MockProvider) Available() bool { return true }

func (m *MockProvider) GetQuote(_ context.Context, reportData [64]byte) (*QuoteResult, error) {
	report := buildMockReport(reportData, m.Name())
	return &QuoteResult{
		Report:    report,
		CertChain: nil,
		AuxBlob:   nil,
	}, nil
}

// buildMockReport creates a synthetic report that mirrors the structure
// of real attestation reports enough to test the control plane:
//   - Bytes 0-3: magic "MOCK"
//   - Bytes 4-7: report length (little-endian uint32)
//   - Bytes 8-11: TEE type tag ("SNP\0" or "TDX\0")
//   - Bytes 12-15: timestamp (unix seconds, little-endian uint32)
//   - Bytes 16-79: zero padding
//   - Bytes 80-143: report_data echo (the tenant's nonce — invariant #5)
//   - Bytes 144-175: SHA-256(report_data) as a fake "measurement"
//   - Bytes 176+: zero padding to total size
//
// For SNP the total is 1184 bytes; for TDX it's 1024 bytes.
func buildMockReport(reportData [64]byte, teeType string) []byte {
	size := 1184 // SNP report size
	if teeType == NameTDX {
		size = 1024
	}

	report := make([]byte, size)

	// Magic
	copy(report[0:4], []byte("MOCK"))

	// Length
	binary.LittleEndian.PutUint32(report[4:8], uint32(size)) //nolint:gosec // size is 1024 or 1184

	// TEE tag
	switch teeType {
	case NameTDX:
		copy(report[8:12], []byte("TDX\x00"))
	default:
		copy(report[8:12], []byte("SNP\x00"))
	}

	// Timestamp
	binary.LittleEndian.PutUint32(report[12:16], uint32(time.Now().Unix())) //nolint:gosec // fits until 2106

	// report_data echo at offset 80 (matches SNP REPORT_DATA offset 0x50)
	copy(report[80:144], reportData[:])

	// Fake measurement at offset 144
	h := sha256.Sum256(reportData[:])
	copy(report[144:176], h[:])

	return report
}

// IsMockReport returns true if the report was generated by MockProvider.
func IsMockReport(report []byte) bool {
	return len(report) >= 4 && string(report[0:4]) == "MOCK"
}

// ExtractMockReportData extracts the report_data (nonce) from a mock report.
func ExtractMockReportData(report []byte) ([64]byte, error) {
	var rd [64]byte
	if len(report) < 144 {
		return rd, fmt.Errorf("report too short: %d bytes", len(report))
	}
	copy(rd[:], report[80:144])
	return rd, nil
}
