package tee

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"time"
)

// MockProvider returns synthetic attestation reports for local development
// and testing without TEE hardware. Activated when ATTESTATION_MOCK=true.
//
// The mock report is deterministic given the same report_data: it embeds
// the nonce in a recognizable structure so tests can verify the nonce echo
// without real hardware.
//
// NEVER use in production. The mock report has no cryptographic validity.
type MockProvider struct {
	TEE      string // "snp" or "tdx" — controls the reported TEE type
	WithGPU  bool   // when true, simulates GPU CC attestation
	GPUCount int    // number of mock GPUs (defaults to 1 if 0)
}

var _ Provider = (*MockProvider)(nil)

func (m *MockProvider) Name() string {
	base := m.TEE
	if base == "" {
		base = NameSNP
	}
	if m.WithGPU {
		switch base {
		case NameTDX:
			return NameTDXGPU
		default:
			return NameSNPGPU
		}
	}
	return base
}

func (m *MockProvider) Available() bool { return true }

func (m *MockProvider) GetQuote(_ context.Context, reportData [64]byte) (*QuoteResult, error) {
	report := buildMockReport(reportData, m.Name())
	result := &QuoteResult{
		Report:    report,
		CertChain: nil,
		AuxBlob:   nil,
	}
	if m.WithGPU {
		gpuCount := m.GPUCount
		if gpuCount <= 0 {
			gpuCount = 1
		}
		result.GPUReports = make([]GPUDeviceReport, gpuCount)
		for i := 0; i < gpuCount; i++ {
			result.GPUReports[i] = GPUDeviceReport{
				DeviceIndex: uint32(i), //nolint:gosec // mock device index
				Report:      buildMockGPUReport(reportData, i),
			}
		}
	}
	return result, nil
}

// buildMockReport creates a synthetic report that mirrors the structure
// of real attestation reports enough to test the control plane:
//   - Bytes 0-3: "MOCK"
//   - Bytes 4-7: report length (little-endian uint32)
//   - Bytes 8-11: TEE type tag ("SNP\0" or "TDX\0")
//   - Bytes 12-15: timestamp (unix seconds, little-endian uint32)
//   - Bytes 16-79: zero padding
//   - Bytes 80-143: report_data echo (the tenant's nonce)
//   - Bytes 144-175: SHA-256(report_data) as a fake "measurement"
//   - Bytes 176+: zero padding to total size
//
// For SNP the total is 1184 bytes; for TDX it's 1024 bytes.
func buildMockReport(reportData [64]byte, teeType string) []byte {
	size := 1184 // SNP report size
	if teeType == NameTDX || teeType == NameTDXGPU {
		size = 1024
	}

	report := make([]byte, size)

	copy(report[0:4], []byte("MOCK"))
	binary.LittleEndian.PutUint32(report[4:8], uint32(size)) //nolint:gosec

	switch teeType {
	case NameTDX, NameTDXGPU:
		copy(report[8:12], []byte("TDX\x00"))
	default:
		copy(report[8:12], []byte("SNP\x00"))
	}

	binary.LittleEndian.PutUint32(report[12:16], uint32(time.Now().Unix())) //nolint:gosec
	copy(report[80:144], reportData[:])

	h := sha256.Sum256(reportData[:])
	copy(report[144:176], h[:])

	return report
}

// buildMockGPUReport creates a synthetic GPU attestation report.
//   - Bytes 0-3: "MGPU"
//   - Bytes 4-7: report length (little-endian uint32)
//   - Bytes 8-11: device index (little-endian uint32)
//   - Bytes 12-75: nonce echo (64 bytes)
//   - Bytes 76-107: SHA-256(nonce) as a fake GPU measurement
//   - Bytes 108+: zero padding to 512 bytes
func buildMockGPUReport(nonce [64]byte, deviceIndex int) []byte {
	const size = 512
	report := make([]byte, size)

	copy(report[0:4], []byte("MGPU"))
	binary.LittleEndian.PutUint32(report[4:8], uint32(size))
	binary.LittleEndian.PutUint32(report[8:12], uint32(deviceIndex)) //nolint:gosec
	copy(report[12:76], nonce[:])

	h := sha256.Sum256(nonce[:])
	copy(report[76:108], h[:])

	return report
}

// IsMockReport returns true if the report was generated by MockProvider.
func IsMockReport(report []byte) bool {
	return len(report) >= 4 && string(report[0:4]) == "MOCK"
}

// ExtractMockReportData extracts the report_data (nonce) from a mock report.
func ExtractMockReportData(report []byte) ([64]byte, error) {
	var rd [64]byte
	if len(report) < 144 {
		return rd, fmt.Errorf("report too short: %d bytes", len(report))
	}
	copy(rd[:], report[80:144])
	return rd, nil
}
