// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	rbacv1beta1 "k8s.io/api/rbac/v1beta1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1beta1 "k8s.io/client-go/applyconfigurations/rbac/v1beta1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// ClusterRoleInterface is an autogenerated mock type for the ClusterRoleInterface type
type ClusterRoleInterface struct {
	mock.Mock
}

type ClusterRoleInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterRoleInterface) EXPECT() *ClusterRoleInterface_Expecter {
	return &ClusterRoleInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, clusterRole, opts
func (_m *ClusterRoleInterface) Apply(ctx context.Context, clusterRole *v1beta1.ClusterRoleApplyConfiguration, opts v1.ApplyOptions) (*rbacv1beta1.ClusterRole, error) {
	ret := _m.Called(ctx, clusterRole, opts)

	var r0 *rbacv1beta1.ClusterRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.ClusterRoleApplyConfiguration, v1.ApplyOptions) (*rbacv1beta1.ClusterRole, error)); ok {
		return rf(ctx, clusterRole, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.ClusterRoleApplyConfiguration, v1.ApplyOptions) *rbacv1beta1.ClusterRole); ok {
		r0 = rf(ctx, clusterRole, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.ClusterRoleApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, clusterRole, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type ClusterRoleInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterRole *v1beta1.ClusterRoleApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *ClusterRoleInterface_Expecter) Apply(ctx interface{}, clusterRole interface{}, opts interface{}) *ClusterRoleInterface_Apply_Call {
	return &ClusterRoleInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, clusterRole, opts)}
}

func (_c *ClusterRoleInterface_Apply_Call) Run(run func(ctx context.Context, clusterRole *v1beta1.ClusterRoleApplyConfiguration, opts v1.ApplyOptions)) *ClusterRoleInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1beta1.ClusterRoleApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Apply_Call) Return(result *rbacv1beta1.ClusterRole, err error) *ClusterRoleInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ClusterRoleInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1beta1.ClusterRoleApplyConfiguration, v1.ApplyOptions) (*rbacv1beta1.ClusterRole, error)) *ClusterRoleInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, clusterRole, opts
func (_m *ClusterRoleInterface) Create(ctx context.Context, clusterRole *rbacv1beta1.ClusterRole, opts v1.CreateOptions) (*rbacv1beta1.ClusterRole, error) {
	ret := _m.Called(ctx, clusterRole, opts)

	var r0 *rbacv1beta1.ClusterRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rbacv1beta1.ClusterRole, v1.CreateOptions) (*rbacv1beta1.ClusterRole, error)); ok {
		return rf(ctx, clusterRole, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rbacv1beta1.ClusterRole, v1.CreateOptions) *rbacv1beta1.ClusterRole); ok {
		r0 = rf(ctx, clusterRole, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rbacv1beta1.ClusterRole, v1.CreateOptions) error); ok {
		r1 = rf(ctx, clusterRole, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClusterRoleInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterRole *rbacv1beta1.ClusterRole
//   - opts v1.CreateOptions
func (_e *ClusterRoleInterface_Expecter) Create(ctx interface{}, clusterRole interface{}, opts interface{}) *ClusterRoleInterface_Create_Call {
	return &ClusterRoleInterface_Create_Call{Call: _e.mock.On("Create", ctx, clusterRole, opts)}
}

func (_c *ClusterRoleInterface_Create_Call) Run(run func(ctx context.Context, clusterRole *rbacv1beta1.ClusterRole, opts v1.CreateOptions)) *ClusterRoleInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*rbacv1beta1.ClusterRole), args[2].(v1.CreateOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Create_Call) Return(_a0 *rbacv1beta1.ClusterRole, _a1 error) *ClusterRoleInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterRoleInterface_Create_Call) RunAndReturn(run func(context.Context, *rbacv1beta1.ClusterRole, v1.CreateOptions) (*rbacv1beta1.ClusterRole, error)) *ClusterRoleInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *ClusterRoleInterface) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterRoleInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClusterRoleInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *ClusterRoleInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *ClusterRoleInterface_Delete_Call {
	return &ClusterRoleInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *ClusterRoleInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *ClusterRoleInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Delete_Call) Return(_a0 error) *ClusterRoleInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterRoleInterface_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *ClusterRoleInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *ClusterRoleInterface) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterRoleInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type ClusterRoleInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *ClusterRoleInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *ClusterRoleInterface_DeleteCollection_Call {
	return &ClusterRoleInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *ClusterRoleInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *ClusterRoleInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_DeleteCollection_Call) Return(_a0 error) *ClusterRoleInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterRoleInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *ClusterRoleInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *ClusterRoleInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*rbacv1beta1.ClusterRole, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *rbacv1beta1.ClusterRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*rbacv1beta1.ClusterRole, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *rbacv1beta1.ClusterRole); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClusterRoleInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *ClusterRoleInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *ClusterRoleInterface_Get_Call {
	return &ClusterRoleInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *ClusterRoleInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *ClusterRoleInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Get_Call) Return(_a0 *rbacv1beta1.ClusterRole, _a1 error) *ClusterRoleInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterRoleInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*rbacv1beta1.ClusterRole, error)) *ClusterRoleInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *ClusterRoleInterface) List(ctx context.Context, opts v1.ListOptions) (*rbacv1beta1.ClusterRoleList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *rbacv1beta1.ClusterRoleList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*rbacv1beta1.ClusterRoleList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *rbacv1beta1.ClusterRoleList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRoleList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ClusterRoleInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *ClusterRoleInterface_Expecter) List(ctx interface{}, opts interface{}) *ClusterRoleInterface_List_Call {
	return &ClusterRoleInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *ClusterRoleInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *ClusterRoleInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_List_Call) Return(_a0 *rbacv1beta1.ClusterRoleList, _a1 error) *ClusterRoleInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterRoleInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*rbacv1beta1.ClusterRoleList, error)) *ClusterRoleInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *ClusterRoleInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*rbacv1beta1.ClusterRole, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *rbacv1beta1.ClusterRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*rbacv1beta1.ClusterRole, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *rbacv1beta1.ClusterRole); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type ClusterRoleInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *ClusterRoleInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *ClusterRoleInterface_Patch_Call {
	return &ClusterRoleInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *ClusterRoleInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *ClusterRoleInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *ClusterRoleInterface_Patch_Call) Return(result *rbacv1beta1.ClusterRole, err error) *ClusterRoleInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ClusterRoleInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*rbacv1beta1.ClusterRole, error)) *ClusterRoleInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, clusterRole, opts
func (_m *ClusterRoleInterface) Update(ctx context.Context, clusterRole *rbacv1beta1.ClusterRole, opts v1.UpdateOptions) (*rbacv1beta1.ClusterRole, error) {
	ret := _m.Called(ctx, clusterRole, opts)

	var r0 *rbacv1beta1.ClusterRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rbacv1beta1.ClusterRole, v1.UpdateOptions) (*rbacv1beta1.ClusterRole, error)); ok {
		return rf(ctx, clusterRole, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rbacv1beta1.ClusterRole, v1.UpdateOptions) *rbacv1beta1.ClusterRole); ok {
		r0 = rf(ctx, clusterRole, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rbacv1beta1.ClusterRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rbacv1beta1.ClusterRole, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, clusterRole, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ClusterRoleInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterRole *rbacv1beta1.ClusterRole
//   - opts v1.UpdateOptions
func (_e *ClusterRoleInterface_Expecter) Update(ctx interface{}, clusterRole interface{}, opts interface{}) *ClusterRoleInterface_Update_Call {
	return &ClusterRoleInterface_Update_Call{Call: _e.mock.On("Update", ctx, clusterRole, opts)}
}

func (_c *ClusterRoleInterface_Update_Call) Run(run func(ctx context.Context, clusterRole *rbacv1beta1.ClusterRole, opts v1.UpdateOptions)) *ClusterRoleInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*rbacv1beta1.ClusterRole), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Update_Call) Return(_a0 *rbacv1beta1.ClusterRole, _a1 error) *ClusterRoleInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterRoleInterface_Update_Call) RunAndReturn(run func(context.Context, *rbacv1beta1.ClusterRole, v1.UpdateOptions) (*rbacv1beta1.ClusterRole, error)) *ClusterRoleInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *ClusterRoleInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterRoleInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type ClusterRoleInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *ClusterRoleInterface_Expecter) Watch(ctx interface{}, opts interface{}) *ClusterRoleInterface_Watch_Call {
	return &ClusterRoleInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *ClusterRoleInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *ClusterRoleInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *ClusterRoleInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *ClusterRoleInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterRoleInterface_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *ClusterRoleInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewClusterRoleInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterRoleInterface creates a new instance of ClusterRoleInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterRoleInterface(t mockConstructorTestingTNewClusterRoleInterface) *ClusterRoleInterface {
	mock := &ClusterRoleInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
