---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service_account.yaml
commonLabels:
  app.kubernetes.io/name: provider
  app.kubernetes.io/instance: provider-service
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: provider
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: provider-boot
    files:
      - run.sh

  - name: provider-client-config
    literals:
      - AKASH_HOME=/home
      - AP_HOME=/home
      - AKASH_FROM=provider
      - AP_FROM=provider
      - AKASH_NODE=http://akash-node:26657
      - AP_NODE=http://akash-node:26657
      - AKASH_CHAIN_ID=local
      - AP_CHAIN_ID=local
      - AKASH_KEYRING_BACKEND=test
      - AP_KEYRING_BACKEND=test

  - name: provider-config
    literals:
      - AP_CLUSTER_K8S=true
      # - AP_INGRESS_STATIC_HOSTS=false
      # - AP_INGRESS_DOMAIN=
      # - AP_INGRESS_EXPOSE_LB_HOSTS=false
      # - AP_DEPLOYMENT_NETWORK_POLICIES_ENABLED=false
      # - AP_MAX_UNIT_CPU=500
      # - AP_MAX_UNIT_MEMORY=1073741824
      # - AP_MAX_UNIT_STORAGE=1073741824
      # - AP_MAX_UNIT_COUNT=10
      # - ap_max_unit_price=10000
      # - AP_MIN_UNIT_CPU=10
      # - AP_MIN_UNIT_MEMORY=1024
      # - AP_MIN_UNIT_STORAGE=1024
      # - AP_MIN_UNIT_COUNT=1
      # - AP_MIN_UNIT_PRICE=1
      # - AP_MAX_GROUP_COUNT=10
      # - AP_MAX_GROUP_UNITS=10
      # - AP_MAX_GROUP_CPU=1000
      # - AP_MAX_GROUP_MEMORY=1073741824
      # - AP_MAX_GROUP_STORAGE=5368709120
      # - AP_MEM_PRICE_MIN=50
      # - AP_MEM_PRICE_MAX=1048576
      # - AP_BID_PRICE_STRATEGY
      # - AP_BID_CPU_SCALE
      # - AP_BID_STORAGE_SCALE
      # - AP_BID_SCRIPT_PATH
      # - AP_BID_SCRIPT_PROCESS-LIMIT
      # - AP_BID_SCRIPT_PROCESS-TIMEOUT
      # - AP_IP_OPERATOR=true

secretGenerator:
  ##
  # required values:
  ##
  - name: provider-keys
    files: []
