---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
  namespace: akash-services
  labels:
    app.kubernetes.io/name: provider
    app.kubernetes.io/instance: provider-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
spec:
  selector:
    app.kubernetes.io/name: provider
    app.kubernetes.io/instance: provider-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
  ports:
    - name: gateway
      port: 8443
    - name: grpc
      port: 8444
