// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// RoleBindingExpansion is an autogenerated mock type for the RoleBindingExpansion type
type RoleBindingExpansion struct {
	mock.Mock
}

type RoleBindingExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleBindingExpansion) EXPECT() *RoleBindingExpansion_Expecter {
	return &RoleBindingExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewRoleBindingExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleBindingExpansion creates a new instance of RoleBindingExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleBindingExpansion(t mockConstructorTestingTNewRoleBindingExpansion) *RoleBindingExpansion {
	mock := &RoleBindingExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
