apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - statefulset.yaml
  - service.yaml
  - service_account.yaml
commonLabels:
  app.kubernetes.io/instance: redis
  app.kubernetes.io/name: redis
