apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: akash-services
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
