apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: akash-services
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          resources:
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: no
            - name: REDIS_PASSWORD
              value: "securepassword"
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "default"
