---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-provisor
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - job.yaml
patches:
  - path: docker-image-feed.yaml
    target:
      kind: Deployment
      group: apps
      name: devkit
      version: v1
  - path: docker-image-fetch.yaml
    target:
      kind: Job
      group: batch
      name: provisor-fetch
      version: v1
