// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"pkg.akt.dev/go/provider/client"
	"pkg.akt.dev/go/provider/v1"
)

// NewGatewayClient creates a new instance of GatewayClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGatewayClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GatewayClient {
	mock := &GatewayClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GatewayClient is an autogenerated mock type for the GatewayClient type
type GatewayClient struct {
	mock.Mock
}

type GatewayClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GatewayClient) EXPECT() *GatewayClient_Expecter {
	return &GatewayClient_Expecter{mock: &_m.Mock}
}

// BidScreening provides a mock function for the type GatewayClient
func (_mock *GatewayClient) BidScreening(context1 context.Context, bidScreeningRequest *v1.BidScreeningRequest) (*v1.BidScreeningResponse, error) {
	ret := _mock.Called(context1, bidScreeningRequest)

	if len(ret) == 0 {
		panic("no return value specified for BidScreening")
	}

	var r0 *v1.BidScreeningResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.BidScreeningRequest) (*v1.BidScreeningResponse, error)); ok {
		return returnFunc(context1, bidScreeningRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.BidScreeningRequest) *v1.BidScreeningResponse); ok {
		r0 = returnFunc(context1, bidScreeningRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BidScreeningResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.BidScreeningRequest) error); ok {
		r1 = returnFunc(context1, bidScreeningRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GatewayClient_BidScreening_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BidScreening'
type GatewayClient_BidScreening_Call struct {
	*mock.Call
}

// BidScreening is a helper method to define mock.On call
//   - context1 context.Context
//   - bidScreeningRequest *v1.BidScreeningRequest
func (_e *GatewayClient_Expecter) BidScreening(context1 interface{}, bidScreeningRequest interface{}) *GatewayClient_BidScreening_Call {
	return &GatewayClient_BidScreening_Call{Call: _e.mock.On("BidScreening", context1, bidScreeningRequest)}
}

func (_c *GatewayClient_BidScreening_Call) Run(run func(context1 context.Context, bidScreeningRequest *v1.BidScreeningRequest)) *GatewayClient_BidScreening_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.BidScreeningRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.BidScreeningRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GatewayClient_BidScreening_Call) Return(bidScreeningResponse *v1.BidScreeningResponse, err error) *GatewayClient_BidScreening_Call {
	_c.Call.Return(bidScreeningResponse, err)
	return _c
}

func (_c *GatewayClient_BidScreening_Call) RunAndReturn(run func(context1 context.Context, bidScreeningRequest *v1.BidScreeningRequest) (*v1.BidScreeningResponse, error)) *GatewayClient_BidScreening_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type GatewayClient
func (_mock *GatewayClient) Status(context1 context.Context) (*rest.ProviderStatus, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *rest.ProviderStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*rest.ProviderStatus, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *rest.ProviderStatus); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.ProviderStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GatewayClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type GatewayClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
func (_e *GatewayClient_Expecter) Status(context1 interface{}) *GatewayClient_Status_Call {
	return &GatewayClient_Status_Call{Call: _e.mock.On("Status", context1)}
}

func (_c *GatewayClient_Status_Call) Run(run func(context1 context.Context)) *GatewayClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GatewayClient_Status_Call) Return(providerStatus *rest.ProviderStatus, err error) *GatewayClient_Status_Call {
	_c.Call.Return(providerStatus, err)
	return _c
}

func (_c *GatewayClient_Status_Call) RunAndReturn(run func(context1 context.Context) (*rest.ProviderStatus, error)) *GatewayClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// StatusV1 provides a mock function for the type GatewayClient
func (_mock *GatewayClient) StatusV1(ctx context.Context) (*v1.Status, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StatusV1")
	}

	var r0 *v1.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v1.Status, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v1.Status); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GatewayClient_StatusV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusV1'
type GatewayClient_StatusV1_Call struct {
	*mock.Call
}

// StatusV1 is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GatewayClient_Expecter) StatusV1(ctx interface{}) *GatewayClient_StatusV1_Call {
	return &GatewayClient_StatusV1_Call{Call: _e.mock.On("StatusV1", ctx)}
}

func (_c *GatewayClient_StatusV1_Call) Run(run func(ctx context.Context)) *GatewayClient_StatusV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GatewayClient_StatusV1_Call) Return(status *v1.Status, err error) *GatewayClient_StatusV1_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *GatewayClient_StatusV1_Call) RunAndReturn(run func(ctx context.Context) (*v1.Status, error)) *GatewayClient_StatusV1_Call {
	_c.Call.Return(run)
	return _c
}
