// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// CronJobExpansion is an autogenerated mock type for the CronJobExpansion type
type CronJobExpansion struct {
	mock.Mock
}

type CronJobExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *CronJobExpansion) EXPECT() *CronJobExpansion_Expecter {
	return &CronJobExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewCronJobExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewCronJobExpansion creates a new instance of CronJobExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCronJobExpansion(t mockConstructorTestingTNewCronJobExpansion) *CronJobExpansion {
	mock := &CronJobExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
