apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - ../../../../../_docs/kustomize/akash-node

configMapGenerator:
  ##
  # cosmos-sdk app config (app.toml) overrides
  ##
  - name: akash-app-config
    behavior: merge
    literals: []
      # - pruning=syncable

  ##
  # tendermint node config (config.toml) overrides
  ##
  - name: akash-config
    behavior: merge
    literals: []
      # - moniker=node0

  - name: akash-data
    behavior: merge
    files:
      - cache/config/genesis.json

secretGenerator:
  - name: akash-keys
    behavior: replace
    files:
      - cache/config/node_key.json
      - cache/config/priv_validator_key.json
      - cache/data/priv_validator_state.json

patchesJson6902:

  ##
  #  Configure gateway host in `gateway-host.yaml`.  This
  #  will be the hostname for rpc over port 80.
  ##

  - path: gateway-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: akash-node
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: akash-node
      version: v1
