// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/core/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// EndpointsInterface is an autogenerated mock type for the EndpointsInterface type
type EndpointsInterface struct {
	mock.Mock
}

type EndpointsInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *EndpointsInterface) EXPECT() *EndpointsInterface_Expecter {
	return &EndpointsInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, endpoints, opts
func (_m *EndpointsInterface) Apply(ctx context.Context, endpoints *v1.EndpointsApplyConfiguration, opts metav1.ApplyOptions) (*corev1.Endpoints, error) {
	ret := _m.Called(ctx, endpoints, opts)

	var r0 *corev1.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.EndpointsApplyConfiguration, metav1.ApplyOptions) (*corev1.Endpoints, error)); ok {
		return rf(ctx, endpoints, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.EndpointsApplyConfiguration, metav1.ApplyOptions) *corev1.Endpoints); ok {
		r0 = rf(ctx, endpoints, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.EndpointsApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, endpoints, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type EndpointsInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoints *v1.EndpointsApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *EndpointsInterface_Expecter) Apply(ctx interface{}, endpoints interface{}, opts interface{}) *EndpointsInterface_Apply_Call {
	return &EndpointsInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, endpoints, opts)}
}

func (_c *EndpointsInterface_Apply_Call) Run(run func(ctx context.Context, endpoints *v1.EndpointsApplyConfiguration, opts metav1.ApplyOptions)) *EndpointsInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.EndpointsApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Apply_Call) Return(result *corev1.Endpoints, err error) *EndpointsInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *EndpointsInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.EndpointsApplyConfiguration, metav1.ApplyOptions) (*corev1.Endpoints, error)) *EndpointsInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, endpoints, opts
func (_m *EndpointsInterface) Create(ctx context.Context, endpoints *corev1.Endpoints, opts metav1.CreateOptions) (*corev1.Endpoints, error) {
	ret := _m.Called(ctx, endpoints, opts)

	var r0 *corev1.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Endpoints, metav1.CreateOptions) (*corev1.Endpoints, error)); ok {
		return rf(ctx, endpoints, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Endpoints, metav1.CreateOptions) *corev1.Endpoints); ok {
		r0 = rf(ctx, endpoints, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Endpoints, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, endpoints, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EndpointsInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoints *corev1.Endpoints
//   - opts metav1.CreateOptions
func (_e *EndpointsInterface_Expecter) Create(ctx interface{}, endpoints interface{}, opts interface{}) *EndpointsInterface_Create_Call {
	return &EndpointsInterface_Create_Call{Call: _e.mock.On("Create", ctx, endpoints, opts)}
}

func (_c *EndpointsInterface_Create_Call) Run(run func(ctx context.Context, endpoints *corev1.Endpoints, opts metav1.CreateOptions)) *EndpointsInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.Endpoints), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Create_Call) Return(_a0 *corev1.Endpoints, _a1 error) *EndpointsInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EndpointsInterface_Create_Call) RunAndReturn(run func(context.Context, *corev1.Endpoints, metav1.CreateOptions) (*corev1.Endpoints, error)) *EndpointsInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *EndpointsInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndpointsInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EndpointsInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *EndpointsInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *EndpointsInterface_Delete_Call {
	return &EndpointsInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *EndpointsInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *EndpointsInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Delete_Call) Return(_a0 error) *EndpointsInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EndpointsInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *EndpointsInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *EndpointsInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndpointsInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type EndpointsInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *EndpointsInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *EndpointsInterface_DeleteCollection_Call {
	return &EndpointsInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *EndpointsInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *EndpointsInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *EndpointsInterface_DeleteCollection_Call) Return(_a0 error) *EndpointsInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EndpointsInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *EndpointsInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *EndpointsInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*corev1.Endpoints, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *corev1.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*corev1.Endpoints, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *corev1.Endpoints); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EndpointsInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *EndpointsInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *EndpointsInterface_Get_Call {
	return &EndpointsInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *EndpointsInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *EndpointsInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Get_Call) Return(_a0 *corev1.Endpoints, _a1 error) *EndpointsInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EndpointsInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*corev1.Endpoints, error)) *EndpointsInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *EndpointsInterface) List(ctx context.Context, opts metav1.ListOptions) (*corev1.EndpointsList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *corev1.EndpointsList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*corev1.EndpointsList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *corev1.EndpointsList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.EndpointsList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EndpointsInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *EndpointsInterface_Expecter) List(ctx interface{}, opts interface{}) *EndpointsInterface_List_Call {
	return &EndpointsInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *EndpointsInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *EndpointsInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *EndpointsInterface_List_Call) Return(_a0 *corev1.EndpointsList, _a1 error) *EndpointsInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EndpointsInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*corev1.EndpointsList, error)) *EndpointsInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *EndpointsInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*corev1.Endpoints, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *corev1.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.Endpoints, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *corev1.Endpoints); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type EndpointsInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *EndpointsInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *EndpointsInterface_Patch_Call {
	return &EndpointsInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *EndpointsInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *EndpointsInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *EndpointsInterface_Patch_Call) Return(result *corev1.Endpoints, err error) *EndpointsInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *EndpointsInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.Endpoints, error)) *EndpointsInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, endpoints, opts
func (_m *EndpointsInterface) Update(ctx context.Context, endpoints *corev1.Endpoints, opts metav1.UpdateOptions) (*corev1.Endpoints, error) {
	ret := _m.Called(ctx, endpoints, opts)

	var r0 *corev1.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Endpoints, metav1.UpdateOptions) (*corev1.Endpoints, error)); ok {
		return rf(ctx, endpoints, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Endpoints, metav1.UpdateOptions) *corev1.Endpoints); ok {
		r0 = rf(ctx, endpoints, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Endpoints, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, endpoints, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EndpointsInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoints *corev1.Endpoints
//   - opts metav1.UpdateOptions
func (_e *EndpointsInterface_Expecter) Update(ctx interface{}, endpoints interface{}, opts interface{}) *EndpointsInterface_Update_Call {
	return &EndpointsInterface_Update_Call{Call: _e.mock.On("Update", ctx, endpoints, opts)}
}

func (_c *EndpointsInterface_Update_Call) Run(run func(ctx context.Context, endpoints *corev1.Endpoints, opts metav1.UpdateOptions)) *EndpointsInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.Endpoints), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Update_Call) Return(_a0 *corev1.Endpoints, _a1 error) *EndpointsInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EndpointsInterface_Update_Call) RunAndReturn(run func(context.Context, *corev1.Endpoints, metav1.UpdateOptions) (*corev1.Endpoints, error)) *EndpointsInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *EndpointsInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndpointsInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type EndpointsInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *EndpointsInterface_Expecter) Watch(ctx interface{}, opts interface{}) *EndpointsInterface_Watch_Call {
	return &EndpointsInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *EndpointsInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *EndpointsInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *EndpointsInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *EndpointsInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EndpointsInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *EndpointsInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewEndpointsInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewEndpointsInterface creates a new instance of EndpointsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEndpointsInterface(t mockConstructorTestingTNewEndpointsInterface) *EndpointsInterface {
	mock := &EndpointsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
