// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// PersistentVolumeClaimExpansion is an autogenerated mock type for the PersistentVolumeClaimExpansion type
type PersistentVolumeClaimExpansion struct {
	mock.Mock
}

type PersistentVolumeClaimExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *PersistentVolumeClaimExpansion) EXPECT() *PersistentVolumeClaimExpansion_Expecter {
	return &PersistentVolumeClaimExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewPersistentVolumeClaimExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewPersistentVolumeClaimExpansion creates a new instance of PersistentVolumeClaimExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPersistentVolumeClaimExpansion(t mockConstructorTestingTNewPersistentVolumeClaimExpansion) *PersistentVolumeClaimExpansion {
	mock := &PersistentVolumeClaimExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
