// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// ReplicationControllerExpansion is an autogenerated mock type for the ReplicationControllerExpansion type
type ReplicationControllerExpansion struct {
	mock.Mock
}

type ReplicationControllerExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *ReplicationControllerExpansion) EXPECT() *ReplicationControllerExpansion_Expecter {
	return &ReplicationControllerExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewReplicationControllerExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewReplicationControllerExpansion creates a new instance of ReplicationControllerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReplicationControllerExpansion(t mockConstructorTestingTNewReplicationControllerExpansion) *ReplicationControllerExpansion {
	mock := &ReplicationControllerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
