// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// ServiceAccountExpansion is an autogenerated mock type for the ServiceAccountExpansion type
type ServiceAccountExpansion struct {
	mock.Mock
}

type ServiceAccountExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceAccountExpansion) EXPECT() *ServiceAccountExpansion_Expecter {
	return &ServiceAccountExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewServiceAccountExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceAccountExpansion creates a new instance of ServiceAccountExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceAccountExpansion(t mockConstructorTestingTNewServiceAccountExpansion) *ServiceAccountExpansion {
	mock := &ServiceAccountExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
