// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1beta3 "github.com/akash-network/akash-api/go/node/market/v1beta3"

	v2beta2 "github.com/akash-network/akash-api/go/manifest/v2beta2"
)

// Deployment is an autogenerated mock type for the Deployment type
type Deployment struct {
	mock.Mock
}

type Deployment_Expecter struct {
	mock *mock.Mock
}

func (_m *Deployment) EXPECT() *Deployment_Expecter {
	return &Deployment_Expecter{mock: &_m.Mock}
}

// LeaseID provides a mock function with given fields:
func (_m *Deployment) LeaseID() v1beta3.LeaseID {
	ret := _m.Called()

	var r0 v1beta3.LeaseID
	if rf, ok := ret.Get(0).(func() v1beta3.LeaseID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v1beta3.LeaseID)
	}

	return r0
}

// Deployment_LeaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaseID'
type Deployment_LeaseID_Call struct {
	*mock.Call
}

// LeaseID is a helper method to define mock.On call
func (_e *Deployment_Expecter) LeaseID() *Deployment_LeaseID_Call {
	return &Deployment_LeaseID_Call{Call: _e.mock.On("LeaseID")}
}

func (_c *Deployment_LeaseID_Call) Run(run func()) *Deployment_LeaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Deployment_LeaseID_Call) Return(_a0 v1beta3.LeaseID) *Deployment_LeaseID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Deployment_LeaseID_Call) RunAndReturn(run func() v1beta3.LeaseID) *Deployment_LeaseID_Call {
	_c.Call.Return(run)
	return _c
}

// ManifestGroup provides a mock function with given fields:
func (_m *Deployment) ManifestGroup() v2beta2.Group {
	ret := _m.Called()

	var r0 v2beta2.Group
	if rf, ok := ret.Get(0).(func() v2beta2.Group); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v2beta2.Group)
	}

	return r0
}

// Deployment_ManifestGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManifestGroup'
type Deployment_ManifestGroup_Call struct {
	*mock.Call
}

// ManifestGroup is a helper method to define mock.On call
func (_e *Deployment_Expecter) ManifestGroup() *Deployment_ManifestGroup_Call {
	return &Deployment_ManifestGroup_Call{Call: _e.mock.On("ManifestGroup")}
}

func (_c *Deployment_ManifestGroup_Call) Run(run func()) *Deployment_ManifestGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Deployment_ManifestGroup_Call) Return(_a0 v2beta2.Group) *Deployment_ManifestGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Deployment_ManifestGroup_Call) RunAndReturn(run func() v2beta2.Group) *Deployment_ManifestGroup_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDeployment interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeployment creates a new instance of Deployment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeployment(t mockConstructorTestingTNewDeployment) *Deployment {
	mock := &Deployment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
