---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-ip
  namespace: akash-services
  labels:
    app.kubernetes.io/name: ip
    app.kubernetes.io/instance: ip-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
