// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// PriorityLevelConfigurationExpansion is an autogenerated mock type for the PriorityLevelConfigurationExpansion type
type PriorityLevelConfigurationExpansion struct {
	mock.Mock
}

type PriorityLevelConfigurationExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *PriorityLevelConfigurationExpansion) EXPECT() *PriorityLevelConfigurationExpansion_Expecter {
	return &PriorityLevelConfigurationExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewPriorityLevelConfigurationExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewPriorityLevelConfigurationExpansion creates a new instance of PriorityLevelConfigurationExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPriorityLevelConfigurationExpansion(t mockConstructorTestingTNewPriorityLevelConfigurationExpansion) *PriorityLevelConfigurationExpansion {
	mock := &PriorityLevelConfigurationExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
