// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/client-go/kubernetes/typed/authorization/v1"
)

// SubjectAccessReviewsGetter is an autogenerated mock type for the SubjectAccessReviewsGetter type
type SubjectAccessReviewsGetter struct {
	mock.Mock
}

type SubjectAccessReviewsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *SubjectAccessReviewsGetter) EXPECT() *SubjectAccessReviewsGetter_Expecter {
	return &SubjectAccessReviewsGetter_Expecter{mock: &_m.Mock}
}

// SubjectAccessReviews provides a mock function with given fields:
func (_m *SubjectAccessReviewsGetter) SubjectAccessReviews() v1.SubjectAccessReviewInterface {
	ret := _m.Called()

	var r0 v1.SubjectAccessReviewInterface
	if rf, ok := ret.Get(0).(func() v1.SubjectAccessReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.SubjectAccessReviewInterface)
		}
	}

	return r0
}

// SubjectAccessReviewsGetter_SubjectAccessReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubjectAccessReviews'
type SubjectAccessReviewsGetter_SubjectAccessReviews_Call struct {
	*mock.Call
}

// SubjectAccessReviews is a helper method to define mock.On call
func (_e *SubjectAccessReviewsGetter_Expecter) SubjectAccessReviews() *SubjectAccessReviewsGetter_SubjectAccessReviews_Call {
	return &SubjectAccessReviewsGetter_SubjectAccessReviews_Call{Call: _e.mock.On("SubjectAccessReviews")}
}

func (_c *SubjectAccessReviewsGetter_SubjectAccessReviews_Call) Run(run func()) *SubjectAccessReviewsGetter_SubjectAccessReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubjectAccessReviewsGetter_SubjectAccessReviews_Call) Return(_a0 v1.SubjectAccessReviewInterface) *SubjectAccessReviewsGetter_SubjectAccessReviews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubjectAccessReviewsGetter_SubjectAccessReviews_Call) RunAndReturn(run func() v1.SubjectAccessReviewInterface) *SubjectAccessReviewsGetter_SubjectAccessReviews_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewSubjectAccessReviewsGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubjectAccessReviewsGetter creates a new instance of SubjectAccessReviewsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubjectAccessReviewsGetter(t mockConstructorTestingTNewSubjectAccessReviewsGetter) *SubjectAccessReviewsGetter {
	mock := &SubjectAccessReviewsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
