apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - ../../../../../_docs/kustomize/akash-operator-ip
patchesJson6902:
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: akash-ip-operator
      version: v1
