---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - ../../../../../_docs/kustomize/akash-operator-ip
patches:
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: operator-ip
      version: v1

configMapGenerator:
  - name: operator-ip
    behavior: merge
    envs:
      - configmap.yaml
