apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - ../../../../../_docs/kustomize/akash-provider
configMapGenerator:

  ##
  # cosmos-sdk client (config.toml) options
  ##
  - name: akash-provider-client-config
    behavior: merge
    literals:
      - node=http://akash-node:26657
      - chain-id=local

  ##
  # Akash provider service option overrides
  ##
  - name: akash-provider-config
    behavior: merge
    literals:
      - ingress-domain=app.localhost
      - cluster-public-hostname=app.localhost
      - cluster-node-port-quantity=100
      - bid-price-strategy=randomRange
      - deployment-runtime-class=none
      # - ingress-static-hosts=false

patchesJson6902:

  ##
  #  Configure gateway host in `gateway-host.yaml`.  Its value
  #  should be the hostname from the on-chain Provider.HostURI
  #  field.
  ##

  - path: gateway-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: akash-provider
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: akash-provider
      version: v1

secretGenerator:

  ##
  # Account key material
  ##

  - name: akash-provider-keys
    behavior: replace
    files:
      - cache/key.txt
      - cache/key-pass.txt
      - cache/provider-cert.pem
