---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - ../../../../../_docs/kustomize/akash-operator-hostname
patches:
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: operator-hostname
      version: v1
