// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// PodSchedulingExpansion is an autogenerated mock type for the PodSchedulingExpansion type
type PodSchedulingExpansion struct {
	mock.Mock
}

type PodSchedulingExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *PodSchedulingExpansion) EXPECT() *PodSchedulingExpansion_Expecter {
	return &PodSchedulingExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewPodSchedulingExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewPodSchedulingExpansion creates a new instance of PodSchedulingExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPodSchedulingExpansion(t mockConstructorTestingTNewPodSchedulingExpansion) *PodSchedulingExpansion {
	mock := &PodSchedulingExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
