// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	resourcev1alpha1 "k8s.io/api/resource/v1alpha1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "k8s.io/client-go/applyconfigurations/resource/v1alpha1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// ResourceClaimTemplateInterface is an autogenerated mock type for the ResourceClaimTemplateInterface type
type ResourceClaimTemplateInterface struct {
	mock.Mock
}

type ResourceClaimTemplateInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceClaimTemplateInterface) EXPECT() *ResourceClaimTemplateInterface_Expecter {
	return &ResourceClaimTemplateInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, resourceClaimTemplate, opts
func (_m *ResourceClaimTemplateInterface) Apply(ctx context.Context, resourceClaimTemplate *v1alpha1.ResourceClaimTemplateApplyConfiguration, opts v1.ApplyOptions) (*resourcev1alpha1.ResourceClaimTemplate, error) {
	ret := _m.Called(ctx, resourceClaimTemplate, opts)

	var r0 *resourcev1alpha1.ResourceClaimTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ResourceClaimTemplateApplyConfiguration, v1.ApplyOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)); ok {
		return rf(ctx, resourceClaimTemplate, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ResourceClaimTemplateApplyConfiguration, v1.ApplyOptions) *resourcev1alpha1.ResourceClaimTemplate); ok {
		r0 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ResourceClaimTemplateApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type ResourceClaimTemplateInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceClaimTemplate *v1alpha1.ResourceClaimTemplateApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Apply(ctx interface{}, resourceClaimTemplate interface{}, opts interface{}) *ResourceClaimTemplateInterface_Apply_Call {
	return &ResourceClaimTemplateInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, resourceClaimTemplate, opts)}
}

func (_c *ResourceClaimTemplateInterface_Apply_Call) Run(run func(ctx context.Context, resourceClaimTemplate *v1alpha1.ResourceClaimTemplateApplyConfiguration, opts v1.ApplyOptions)) *ResourceClaimTemplateInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ResourceClaimTemplateApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Apply_Call) Return(result *resourcev1alpha1.ResourceClaimTemplate, err error) *ResourceClaimTemplateInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1alpha1.ResourceClaimTemplateApplyConfiguration, v1.ApplyOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)) *ResourceClaimTemplateInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, resourceClaimTemplate, opts
func (_m *ResourceClaimTemplateInterface) Create(ctx context.Context, resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate, opts v1.CreateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error) {
	ret := _m.Called(ctx, resourceClaimTemplate, opts)

	var r0 *resourcev1alpha1.ResourceClaimTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.CreateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)); ok {
		return rf(ctx, resourceClaimTemplate, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.CreateOptions) *resourcev1alpha1.ResourceClaimTemplate); ok {
		r0 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.CreateOptions) error); ok {
		r1 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResourceClaimTemplateInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate
//   - opts v1.CreateOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Create(ctx interface{}, resourceClaimTemplate interface{}, opts interface{}) *ResourceClaimTemplateInterface_Create_Call {
	return &ResourceClaimTemplateInterface_Create_Call{Call: _e.mock.On("Create", ctx, resourceClaimTemplate, opts)}
}

func (_c *ResourceClaimTemplateInterface_Create_Call) Run(run func(ctx context.Context, resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate, opts v1.CreateOptions)) *ResourceClaimTemplateInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*resourcev1alpha1.ResourceClaimTemplate), args[2].(v1.CreateOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Create_Call) Return(_a0 *resourcev1alpha1.ResourceClaimTemplate, _a1 error) *ResourceClaimTemplateInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Create_Call) RunAndReturn(run func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.CreateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)) *ResourceClaimTemplateInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *ResourceClaimTemplateInterface) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceClaimTemplateInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ResourceClaimTemplateInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *ResourceClaimTemplateInterface_Delete_Call {
	return &ResourceClaimTemplateInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *ResourceClaimTemplateInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *ResourceClaimTemplateInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Delete_Call) Return(_a0 error) *ResourceClaimTemplateInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *ResourceClaimTemplateInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *ResourceClaimTemplateInterface) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceClaimTemplateInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type ResourceClaimTemplateInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *ResourceClaimTemplateInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *ResourceClaimTemplateInterface_DeleteCollection_Call {
	return &ResourceClaimTemplateInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *ResourceClaimTemplateInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *ResourceClaimTemplateInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_DeleteCollection_Call) Return(_a0 error) *ResourceClaimTemplateInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceClaimTemplateInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *ResourceClaimTemplateInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *ResourceClaimTemplateInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*resourcev1alpha1.ResourceClaimTemplate, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *resourcev1alpha1.ResourceClaimTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *resourcev1alpha1.ResourceClaimTemplate); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ResourceClaimTemplateInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *ResourceClaimTemplateInterface_Get_Call {
	return &ResourceClaimTemplateInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *ResourceClaimTemplateInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *ResourceClaimTemplateInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Get_Call) Return(_a0 *resourcev1alpha1.ResourceClaimTemplate, _a1 error) *ResourceClaimTemplateInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)) *ResourceClaimTemplateInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *ResourceClaimTemplateInterface) List(ctx context.Context, opts v1.ListOptions) (*resourcev1alpha1.ResourceClaimTemplateList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *resourcev1alpha1.ResourceClaimTemplateList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*resourcev1alpha1.ResourceClaimTemplateList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *resourcev1alpha1.ResourceClaimTemplateList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplateList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ResourceClaimTemplateInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *ResourceClaimTemplateInterface_Expecter) List(ctx interface{}, opts interface{}) *ResourceClaimTemplateInterface_List_Call {
	return &ResourceClaimTemplateInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *ResourceClaimTemplateInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *ResourceClaimTemplateInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_List_Call) Return(_a0 *resourcev1alpha1.ResourceClaimTemplateList, _a1 error) *ResourceClaimTemplateInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceClaimTemplateInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*resourcev1alpha1.ResourceClaimTemplateList, error)) *ResourceClaimTemplateInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *ResourceClaimTemplateInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*resourcev1alpha1.ResourceClaimTemplate, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *resourcev1alpha1.ResourceClaimTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*resourcev1alpha1.ResourceClaimTemplate, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *resourcev1alpha1.ResourceClaimTemplate); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type ResourceClaimTemplateInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *ResourceClaimTemplateInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *ResourceClaimTemplateInterface_Patch_Call {
	return &ResourceClaimTemplateInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *ResourceClaimTemplateInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *ResourceClaimTemplateInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Patch_Call) Return(result *resourcev1alpha1.ResourceClaimTemplate, err error) *ResourceClaimTemplateInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*resourcev1alpha1.ResourceClaimTemplate, error)) *ResourceClaimTemplateInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, resourceClaimTemplate, opts
func (_m *ResourceClaimTemplateInterface) Update(ctx context.Context, resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate, opts v1.UpdateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error) {
	ret := _m.Called(ctx, resourceClaimTemplate, opts)

	var r0 *resourcev1alpha1.ResourceClaimTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.UpdateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)); ok {
		return rf(ctx, resourceClaimTemplate, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.UpdateOptions) *resourcev1alpha1.ResourceClaimTemplate); ok {
		r0 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcev1alpha1.ResourceClaimTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, resourceClaimTemplate, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ResourceClaimTemplateInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate
//   - opts v1.UpdateOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Update(ctx interface{}, resourceClaimTemplate interface{}, opts interface{}) *ResourceClaimTemplateInterface_Update_Call {
	return &ResourceClaimTemplateInterface_Update_Call{Call: _e.mock.On("Update", ctx, resourceClaimTemplate, opts)}
}

func (_c *ResourceClaimTemplateInterface_Update_Call) Run(run func(ctx context.Context, resourceClaimTemplate *resourcev1alpha1.ResourceClaimTemplate, opts v1.UpdateOptions)) *ResourceClaimTemplateInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*resourcev1alpha1.ResourceClaimTemplate), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Update_Call) Return(_a0 *resourcev1alpha1.ResourceClaimTemplate, _a1 error) *ResourceClaimTemplateInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Update_Call) RunAndReturn(run func(context.Context, *resourcev1alpha1.ResourceClaimTemplate, v1.UpdateOptions) (*resourcev1alpha1.ResourceClaimTemplate, error)) *ResourceClaimTemplateInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *ResourceClaimTemplateInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceClaimTemplateInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type ResourceClaimTemplateInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *ResourceClaimTemplateInterface_Expecter) Watch(ctx interface{}, opts interface{}) *ResourceClaimTemplateInterface_Watch_Call {
	return &ResourceClaimTemplateInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *ResourceClaimTemplateInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *ResourceClaimTemplateInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *ResourceClaimTemplateInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *ResourceClaimTemplateInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceClaimTemplateInterface_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *ResourceClaimTemplateInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewResourceClaimTemplateInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewResourceClaimTemplateInterface creates a new instance of ResourceClaimTemplateInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResourceClaimTemplateInterface(t mockConstructorTestingTNewResourceClaimTemplateInterface) *ResourceClaimTemplateInterface {
	mock := &ResourceClaimTemplateInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
