// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// VolumeAttachmentExpansion is an autogenerated mock type for the VolumeAttachmentExpansion type
type VolumeAttachmentExpansion struct {
	mock.Mock
}

type VolumeAttachmentExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *VolumeAttachmentExpansion) EXPECT() *VolumeAttachmentExpansion_Expecter {
	return &VolumeAttachmentExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewVolumeAttachmentExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewVolumeAttachmentExpansion creates a new instance of VolumeAttachmentExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVolumeAttachmentExpansion(t mockConstructorTestingTNewVolumeAttachmentExpansion) *VolumeAttachmentExpansion {
	mock := &VolumeAttachmentExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
