/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

// ManifestStorageParamsApplyConfiguration represents a declarative configuration of the ManifestStorageParams type for use
// with apply.
type ManifestStorageParamsApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Mount    *string `json:"mount,omitempty"`
	ReadOnly *bool   `json:"readOnly,omitempty"`
}

// ManifestStorageParamsApplyConfiguration constructs a declarative configuration of the ManifestStorageParams type for use with
// apply.
func ManifestStorageParams() *ManifestStorageParamsApplyConfiguration {
	return &ManifestStorageParamsApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ManifestStorageParamsApplyConfiguration) WithName(value string) *ManifestStorageParamsApplyConfiguration {
	b.Name = &value
	return b
}

// WithMount sets the Mount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mount field is set to the value of the last call.
func (b *ManifestStorageParamsApplyConfiguration) WithMount(value string) *ManifestStorageParamsApplyConfiguration {
	b.Mount = &value
	return b
}

// WithReadOnly sets the ReadOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadOnly field is set to the value of the last call.
func (b *ManifestStorageParamsApplyConfiguration) WithReadOnly(value bool) *ManifestStorageParamsApplyConfiguration {
	b.ReadOnly = &value
	return b
}
