---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NGINX Gateway Fabric deployment (NodePort variant)
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.4.1/deploy/nodeport/deploy.yaml
  # Akash gateway resources (namespace + Gateway)
  - gateway.yaml
patches:
  - path: nodeport-patch.yaml
