// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// ValidatingWebhookConfigurationExpansion is an autogenerated mock type for the ValidatingWebhookConfigurationExpansion type
type ValidatingWebhookConfigurationExpansion struct {
	mock.Mock
}

type ValidatingWebhookConfigurationExpansion_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidatingWebhookConfigurationExpansion) EXPECT() *ValidatingWebhookConfigurationExpansion_Expecter {
	return &ValidatingWebhookConfigurationExpansion_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewValidatingWebhookConfigurationExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidatingWebhookConfigurationExpansion creates a new instance of ValidatingWebhookConfigurationExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidatingWebhookConfigurationExpansion(t mockConstructorTestingTNewValidatingWebhookConfigurationExpansion) *ValidatingWebhookConfigurationExpansion {
	mock := &ValidatingWebhookConfigurationExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
