// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1beta1 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"
)

// StorageV1beta1Interface is an autogenerated mock type for the StorageV1beta1Interface type
type StorageV1beta1Interface struct {
	mock.Mock
}

type StorageV1beta1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageV1beta1Interface) EXPECT() *StorageV1beta1Interface_Expecter {
	return &StorageV1beta1Interface_Expecter{mock: &_m.Mock}
}

// CSIDrivers provides a mock function with given fields:
func (_m *StorageV1beta1Interface) CSIDrivers() v1beta1.CSIDriverInterface {
	ret := _m.Called()

	var r0 v1beta1.CSIDriverInterface
	if rf, ok := ret.Get(0).(func() v1beta1.CSIDriverInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.CSIDriverInterface)
		}
	}

	return r0
}

// StorageV1beta1Interface_CSIDrivers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CSIDrivers'
type StorageV1beta1Interface_CSIDrivers_Call struct {
	*mock.Call
}

// CSIDrivers is a helper method to define mock.On call
func (_e *StorageV1beta1Interface_Expecter) CSIDrivers() *StorageV1beta1Interface_CSIDrivers_Call {
	return &StorageV1beta1Interface_CSIDrivers_Call{Call: _e.mock.On("CSIDrivers")}
}

func (_c *StorageV1beta1Interface_CSIDrivers_Call) Run(run func()) *StorageV1beta1Interface_CSIDrivers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageV1beta1Interface_CSIDrivers_Call) Return(_a0 v1beta1.CSIDriverInterface) *StorageV1beta1Interface_CSIDrivers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_CSIDrivers_Call) RunAndReturn(run func() v1beta1.CSIDriverInterface) *StorageV1beta1Interface_CSIDrivers_Call {
	_c.Call.Return(run)
	return _c
}

// CSINodes provides a mock function with given fields:
func (_m *StorageV1beta1Interface) CSINodes() v1beta1.CSINodeInterface {
	ret := _m.Called()

	var r0 v1beta1.CSINodeInterface
	if rf, ok := ret.Get(0).(func() v1beta1.CSINodeInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.CSINodeInterface)
		}
	}

	return r0
}

// StorageV1beta1Interface_CSINodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CSINodes'
type StorageV1beta1Interface_CSINodes_Call struct {
	*mock.Call
}

// CSINodes is a helper method to define mock.On call
func (_e *StorageV1beta1Interface_Expecter) CSINodes() *StorageV1beta1Interface_CSINodes_Call {
	return &StorageV1beta1Interface_CSINodes_Call{Call: _e.mock.On("CSINodes")}
}

func (_c *StorageV1beta1Interface_CSINodes_Call) Run(run func()) *StorageV1beta1Interface_CSINodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageV1beta1Interface_CSINodes_Call) Return(_a0 v1beta1.CSINodeInterface) *StorageV1beta1Interface_CSINodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_CSINodes_Call) RunAndReturn(run func() v1beta1.CSINodeInterface) *StorageV1beta1Interface_CSINodes_Call {
	_c.Call.Return(run)
	return _c
}

// CSIStorageCapacities provides a mock function with given fields: namespace
func (_m *StorageV1beta1Interface) CSIStorageCapacities(namespace string) v1beta1.CSIStorageCapacityInterface {
	ret := _m.Called(namespace)

	var r0 v1beta1.CSIStorageCapacityInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.CSIStorageCapacityInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.CSIStorageCapacityInterface)
		}
	}

	return r0
}

// StorageV1beta1Interface_CSIStorageCapacities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CSIStorageCapacities'
type StorageV1beta1Interface_CSIStorageCapacities_Call struct {
	*mock.Call
}

// CSIStorageCapacities is a helper method to define mock.On call
//   - namespace string
func (_e *StorageV1beta1Interface_Expecter) CSIStorageCapacities(namespace interface{}) *StorageV1beta1Interface_CSIStorageCapacities_Call {
	return &StorageV1beta1Interface_CSIStorageCapacities_Call{Call: _e.mock.On("CSIStorageCapacities", namespace)}
}

func (_c *StorageV1beta1Interface_CSIStorageCapacities_Call) Run(run func(namespace string)) *StorageV1beta1Interface_CSIStorageCapacities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageV1beta1Interface_CSIStorageCapacities_Call) Return(_a0 v1beta1.CSIStorageCapacityInterface) *StorageV1beta1Interface_CSIStorageCapacities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_CSIStorageCapacities_Call) RunAndReturn(run func(string) v1beta1.CSIStorageCapacityInterface) *StorageV1beta1Interface_CSIStorageCapacities_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with given fields:
func (_m *StorageV1beta1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// StorageV1beta1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type StorageV1beta1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *StorageV1beta1Interface_Expecter) RESTClient() *StorageV1beta1Interface_RESTClient_Call {
	return &StorageV1beta1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *StorageV1beta1Interface_RESTClient_Call) Run(run func()) *StorageV1beta1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageV1beta1Interface_RESTClient_Call) Return(_a0 rest.Interface) *StorageV1beta1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *StorageV1beta1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// StorageClasses provides a mock function with given fields:
func (_m *StorageV1beta1Interface) StorageClasses() v1beta1.StorageClassInterface {
	ret := _m.Called()

	var r0 v1beta1.StorageClassInterface
	if rf, ok := ret.Get(0).(func() v1beta1.StorageClassInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.StorageClassInterface)
		}
	}

	return r0
}

// StorageV1beta1Interface_StorageClasses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageClasses'
type StorageV1beta1Interface_StorageClasses_Call struct {
	*mock.Call
}

// StorageClasses is a helper method to define mock.On call
func (_e *StorageV1beta1Interface_Expecter) StorageClasses() *StorageV1beta1Interface_StorageClasses_Call {
	return &StorageV1beta1Interface_StorageClasses_Call{Call: _e.mock.On("StorageClasses")}
}

func (_c *StorageV1beta1Interface_StorageClasses_Call) Run(run func()) *StorageV1beta1Interface_StorageClasses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageV1beta1Interface_StorageClasses_Call) Return(_a0 v1beta1.StorageClassInterface) *StorageV1beta1Interface_StorageClasses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_StorageClasses_Call) RunAndReturn(run func() v1beta1.StorageClassInterface) *StorageV1beta1Interface_StorageClasses_Call {
	_c.Call.Return(run)
	return _c
}

// VolumeAttachments provides a mock function with given fields:
func (_m *StorageV1beta1Interface) VolumeAttachments() v1beta1.VolumeAttachmentInterface {
	ret := _m.Called()

	var r0 v1beta1.VolumeAttachmentInterface
	if rf, ok := ret.Get(0).(func() v1beta1.VolumeAttachmentInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.VolumeAttachmentInterface)
		}
	}

	return r0
}

// StorageV1beta1Interface_VolumeAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VolumeAttachments'
type StorageV1beta1Interface_VolumeAttachments_Call struct {
	*mock.Call
}

// VolumeAttachments is a helper method to define mock.On call
func (_e *StorageV1beta1Interface_Expecter) VolumeAttachments() *StorageV1beta1Interface_VolumeAttachments_Call {
	return &StorageV1beta1Interface_VolumeAttachments_Call{Call: _e.mock.On("VolumeAttachments")}
}

func (_c *StorageV1beta1Interface_VolumeAttachments_Call) Run(run func()) *StorageV1beta1Interface_VolumeAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageV1beta1Interface_VolumeAttachments_Call) Return(_a0 v1beta1.VolumeAttachmentInterface) *StorageV1beta1Interface_VolumeAttachments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageV1beta1Interface_VolumeAttachments_Call) RunAndReturn(run func() v1beta1.VolumeAttachmentInterface) *StorageV1beta1Interface_VolumeAttachments_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStorageV1beta1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageV1beta1Interface creates a new instance of StorageV1beta1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageV1beta1Interface(t mockConstructorTestingTNewStorageV1beta1Interface) *StorageV1beta1Interface {
	mock := &StorageV1beta1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
