apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-discovery
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: discovery
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
