/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	akashnetworkv2beta1 "github.com/akash-network/provider/pkg/apis/akash.network/v2beta1"
	applyconfigurationakashnetworkv2beta1 "github.com/akash-network/provider/pkg/client/applyconfiguration/akash.network/v2beta1"
	scheme "github.com/akash-network/provider/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProviderLeasedIPsGetter has a method to return a ProviderLeasedIPInterface.
// A group's client should implement this interface.
type ProviderLeasedIPsGetter interface {
	ProviderLeasedIPs(namespace string) ProviderLeasedIPInterface
}

// ProviderLeasedIPInterface has methods to work with ProviderLeasedIP resources.
type ProviderLeasedIPInterface interface {
	Create(ctx context.Context, providerLeasedIP *akashnetworkv2beta1.ProviderLeasedIP, opts v1.CreateOptions) (*akashnetworkv2beta1.ProviderLeasedIP, error)
	Update(ctx context.Context, providerLeasedIP *akashnetworkv2beta1.ProviderLeasedIP, opts v1.UpdateOptions) (*akashnetworkv2beta1.ProviderLeasedIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, providerLeasedIP *akashnetworkv2beta1.ProviderLeasedIP, opts v1.UpdateOptions) (*akashnetworkv2beta1.ProviderLeasedIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*akashnetworkv2beta1.ProviderLeasedIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*akashnetworkv2beta1.ProviderLeasedIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *akashnetworkv2beta1.ProviderLeasedIP, err error)
	Apply(ctx context.Context, providerLeasedIP *applyconfigurationakashnetworkv2beta1.ProviderLeasedIPApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta1.ProviderLeasedIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, providerLeasedIP *applyconfigurationakashnetworkv2beta1.ProviderLeasedIPApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta1.ProviderLeasedIP, err error)
	ProviderLeasedIPExpansion
}

// providerLeasedIPs implements ProviderLeasedIPInterface
type providerLeasedIPs struct {
	*gentype.ClientWithListAndApply[*akashnetworkv2beta1.ProviderLeasedIP, *akashnetworkv2beta1.ProviderLeasedIPList, *applyconfigurationakashnetworkv2beta1.ProviderLeasedIPApplyConfiguration]
}

// newProviderLeasedIPs returns a ProviderLeasedIPs
func newProviderLeasedIPs(c *AkashV2beta1Client, namespace string) *providerLeasedIPs {
	return &providerLeasedIPs{
		gentype.NewClientWithListAndApply[*akashnetworkv2beta1.ProviderLeasedIP, *akashnetworkv2beta1.ProviderLeasedIPList, *applyconfigurationakashnetworkv2beta1.ProviderLeasedIPApplyConfiguration](
			"providerleasedips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *akashnetworkv2beta1.ProviderLeasedIP { return &akashnetworkv2beta1.ProviderLeasedIP{} },
			func() *akashnetworkv2beta1.ProviderLeasedIPList { return &akashnetworkv2beta1.ProviderLeasedIPList{} },
		),
	}
}
