// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	v2beta2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
)

// HorizontalPodAutoscalersGetter is an autogenerated mock type for the HorizontalPodAutoscalersGetter type
type HorizontalPodAutoscalersGetter struct {
	mock.Mock
}

type HorizontalPodAutoscalersGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *HorizontalPodAutoscalersGetter) EXPECT() *HorizontalPodAutoscalersGetter_Expecter {
	return &HorizontalPodAutoscalersGetter_Expecter{mock: &_m.Mock}
}

// HorizontalPodAutoscalers provides a mock function with given fields: namespace
func (_m *HorizontalPodAutoscalersGetter) HorizontalPodAutoscalers(namespace string) v2beta2.HorizontalPodAutoscalerInterface {
	ret := _m.Called(namespace)

	var r0 v2beta2.HorizontalPodAutoscalerInterface
	if rf, ok := ret.Get(0).(func(string) v2beta2.HorizontalPodAutoscalerInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta2.HorizontalPodAutoscalerInterface)
		}
	}

	return r0
}

// HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HorizontalPodAutoscalers'
type HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call struct {
	*mock.Call
}

// HorizontalPodAutoscalers is a helper method to define mock.On call
//   - namespace string
func (_e *HorizontalPodAutoscalersGetter_Expecter) HorizontalPodAutoscalers(namespace interface{}) *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call {
	return &HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call{Call: _e.mock.On("HorizontalPodAutoscalers", namespace)}
}

func (_c *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call) Run(run func(namespace string)) *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call) Return(_a0 v2beta2.HorizontalPodAutoscalerInterface) *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call) RunAndReturn(run func(string) v2beta2.HorizontalPodAutoscalerInterface) *HorizontalPodAutoscalersGetter_HorizontalPodAutoscalers_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHorizontalPodAutoscalersGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewHorizontalPodAutoscalersGetter creates a new instance of HorizontalPodAutoscalersGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHorizontalPodAutoscalersGetter(t mockConstructorTestingTNewHorizontalPodAutoscalersGetter) *HorizontalPodAutoscalersGetter {
	mock := &HorizontalPodAutoscalersGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
