// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	nodev1 "k8s.io/api/node/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/node/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// RuntimeClassInterface is an autogenerated mock type for the RuntimeClassInterface type
type RuntimeClassInterface struct {
	mock.Mock
}

type RuntimeClassInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RuntimeClassInterface) EXPECT() *RuntimeClassInterface_Expecter {
	return &RuntimeClassInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, runtimeClass, opts
func (_m *RuntimeClassInterface) Apply(ctx context.Context, runtimeClass *v1.RuntimeClassApplyConfiguration, opts metav1.ApplyOptions) (*nodev1.RuntimeClass, error) {
	ret := _m.Called(ctx, runtimeClass, opts)

	var r0 *nodev1.RuntimeClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RuntimeClassApplyConfiguration, metav1.ApplyOptions) (*nodev1.RuntimeClass, error)); ok {
		return rf(ctx, runtimeClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RuntimeClassApplyConfiguration, metav1.ApplyOptions) *nodev1.RuntimeClass); ok {
		r0 = rf(ctx, runtimeClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RuntimeClassApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, runtimeClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type RuntimeClassInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - runtimeClass *v1.RuntimeClassApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *RuntimeClassInterface_Expecter) Apply(ctx interface{}, runtimeClass interface{}, opts interface{}) *RuntimeClassInterface_Apply_Call {
	return &RuntimeClassInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, runtimeClass, opts)}
}

func (_c *RuntimeClassInterface_Apply_Call) Run(run func(ctx context.Context, runtimeClass *v1.RuntimeClassApplyConfiguration, opts metav1.ApplyOptions)) *RuntimeClassInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.RuntimeClassApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Apply_Call) Return(result *nodev1.RuntimeClass, err error) *RuntimeClassInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *RuntimeClassInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.RuntimeClassApplyConfiguration, metav1.ApplyOptions) (*nodev1.RuntimeClass, error)) *RuntimeClassInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, runtimeClass, opts
func (_m *RuntimeClassInterface) Create(ctx context.Context, runtimeClass *nodev1.RuntimeClass, opts metav1.CreateOptions) (*nodev1.RuntimeClass, error) {
	ret := _m.Called(ctx, runtimeClass, opts)

	var r0 *nodev1.RuntimeClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *nodev1.RuntimeClass, metav1.CreateOptions) (*nodev1.RuntimeClass, error)); ok {
		return rf(ctx, runtimeClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *nodev1.RuntimeClass, metav1.CreateOptions) *nodev1.RuntimeClass); ok {
		r0 = rf(ctx, runtimeClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *nodev1.RuntimeClass, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, runtimeClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RuntimeClassInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - runtimeClass *nodev1.RuntimeClass
//   - opts metav1.CreateOptions
func (_e *RuntimeClassInterface_Expecter) Create(ctx interface{}, runtimeClass interface{}, opts interface{}) *RuntimeClassInterface_Create_Call {
	return &RuntimeClassInterface_Create_Call{Call: _e.mock.On("Create", ctx, runtimeClass, opts)}
}

func (_c *RuntimeClassInterface_Create_Call) Run(run func(ctx context.Context, runtimeClass *nodev1.RuntimeClass, opts metav1.CreateOptions)) *RuntimeClassInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*nodev1.RuntimeClass), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Create_Call) Return(_a0 *nodev1.RuntimeClass, _a1 error) *RuntimeClassInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuntimeClassInterface_Create_Call) RunAndReturn(run func(context.Context, *nodev1.RuntimeClass, metav1.CreateOptions) (*nodev1.RuntimeClass, error)) *RuntimeClassInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *RuntimeClassInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuntimeClassInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RuntimeClassInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *RuntimeClassInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *RuntimeClassInterface_Delete_Call {
	return &RuntimeClassInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *RuntimeClassInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *RuntimeClassInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Delete_Call) Return(_a0 error) *RuntimeClassInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuntimeClassInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *RuntimeClassInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *RuntimeClassInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuntimeClassInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type RuntimeClassInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *RuntimeClassInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *RuntimeClassInterface_DeleteCollection_Call {
	return &RuntimeClassInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *RuntimeClassInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *RuntimeClassInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_DeleteCollection_Call) Return(_a0 error) *RuntimeClassInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuntimeClassInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *RuntimeClassInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *RuntimeClassInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*nodev1.RuntimeClass, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *nodev1.RuntimeClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*nodev1.RuntimeClass, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *nodev1.RuntimeClass); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RuntimeClassInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *RuntimeClassInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *RuntimeClassInterface_Get_Call {
	return &RuntimeClassInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *RuntimeClassInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *RuntimeClassInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Get_Call) Return(_a0 *nodev1.RuntimeClass, _a1 error) *RuntimeClassInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuntimeClassInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*nodev1.RuntimeClass, error)) *RuntimeClassInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *RuntimeClassInterface) List(ctx context.Context, opts metav1.ListOptions) (*nodev1.RuntimeClassList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *nodev1.RuntimeClassList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*nodev1.RuntimeClassList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *nodev1.RuntimeClassList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClassList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RuntimeClassInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *RuntimeClassInterface_Expecter) List(ctx interface{}, opts interface{}) *RuntimeClassInterface_List_Call {
	return &RuntimeClassInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *RuntimeClassInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *RuntimeClassInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_List_Call) Return(_a0 *nodev1.RuntimeClassList, _a1 error) *RuntimeClassInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuntimeClassInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*nodev1.RuntimeClassList, error)) *RuntimeClassInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *RuntimeClassInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*nodev1.RuntimeClass, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *nodev1.RuntimeClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*nodev1.RuntimeClass, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *nodev1.RuntimeClass); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type RuntimeClassInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *RuntimeClassInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *RuntimeClassInterface_Patch_Call {
	return &RuntimeClassInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *RuntimeClassInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *RuntimeClassInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *RuntimeClassInterface_Patch_Call) Return(result *nodev1.RuntimeClass, err error) *RuntimeClassInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *RuntimeClassInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*nodev1.RuntimeClass, error)) *RuntimeClassInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, runtimeClass, opts
func (_m *RuntimeClassInterface) Update(ctx context.Context, runtimeClass *nodev1.RuntimeClass, opts metav1.UpdateOptions) (*nodev1.RuntimeClass, error) {
	ret := _m.Called(ctx, runtimeClass, opts)

	var r0 *nodev1.RuntimeClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *nodev1.RuntimeClass, metav1.UpdateOptions) (*nodev1.RuntimeClass, error)); ok {
		return rf(ctx, runtimeClass, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *nodev1.RuntimeClass, metav1.UpdateOptions) *nodev1.RuntimeClass); ok {
		r0 = rf(ctx, runtimeClass, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nodev1.RuntimeClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *nodev1.RuntimeClass, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, runtimeClass, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RuntimeClassInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - runtimeClass *nodev1.RuntimeClass
//   - opts metav1.UpdateOptions
func (_e *RuntimeClassInterface_Expecter) Update(ctx interface{}, runtimeClass interface{}, opts interface{}) *RuntimeClassInterface_Update_Call {
	return &RuntimeClassInterface_Update_Call{Call: _e.mock.On("Update", ctx, runtimeClass, opts)}
}

func (_c *RuntimeClassInterface_Update_Call) Run(run func(ctx context.Context, runtimeClass *nodev1.RuntimeClass, opts metav1.UpdateOptions)) *RuntimeClassInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*nodev1.RuntimeClass), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Update_Call) Return(_a0 *nodev1.RuntimeClass, _a1 error) *RuntimeClassInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuntimeClassInterface_Update_Call) RunAndReturn(run func(context.Context, *nodev1.RuntimeClass, metav1.UpdateOptions) (*nodev1.RuntimeClass, error)) *RuntimeClassInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *RuntimeClassInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuntimeClassInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type RuntimeClassInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *RuntimeClassInterface_Expecter) Watch(ctx interface{}, opts interface{}) *RuntimeClassInterface_Watch_Call {
	return &RuntimeClassInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *RuntimeClassInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *RuntimeClassInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *RuntimeClassInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *RuntimeClassInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuntimeClassInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *RuntimeClassInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRuntimeClassInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRuntimeClassInterface creates a new instance of RuntimeClassInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRuntimeClassInterface(t mockConstructorTestingTNewRuntimeClassInterface) *RuntimeClassInterface {
	mock := &RuntimeClassInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
