---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-hostname
data:
  ingress-mode: gateway-api
  gateway-name: akash-gateway
  gateway-namespace: akash-gateway
  gateway-implementation: nginx


