// Code generated by mockery v2.23.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1alpha1 "k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1"
)

// InternalV1alpha1Interface is an autogenerated mock type for the InternalV1alpha1Interface type
type InternalV1alpha1Interface struct {
	mock.Mock
}

type InternalV1alpha1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalV1alpha1Interface) EXPECT() *InternalV1alpha1Interface_Expecter {
	return &InternalV1alpha1Interface_Expecter{mock: &_m.Mock}
}

// RESTClient provides a mock function with given fields:
func (_m *InternalV1alpha1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// InternalV1alpha1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type InternalV1alpha1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *InternalV1alpha1Interface_Expecter) RESTClient() *InternalV1alpha1Interface_RESTClient_Call {
	return &InternalV1alpha1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *InternalV1alpha1Interface_RESTClient_Call) Run(run func()) *InternalV1alpha1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InternalV1alpha1Interface_RESTClient_Call) Return(_a0 rest.Interface) *InternalV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InternalV1alpha1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *InternalV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// StorageVersions provides a mock function with given fields:
func (_m *InternalV1alpha1Interface) StorageVersions() v1alpha1.StorageVersionInterface {
	ret := _m.Called()

	var r0 v1alpha1.StorageVersionInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.StorageVersionInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.StorageVersionInterface)
		}
	}

	return r0
}

// InternalV1alpha1Interface_StorageVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageVersions'
type InternalV1alpha1Interface_StorageVersions_Call struct {
	*mock.Call
}

// StorageVersions is a helper method to define mock.On call
func (_e *InternalV1alpha1Interface_Expecter) StorageVersions() *InternalV1alpha1Interface_StorageVersions_Call {
	return &InternalV1alpha1Interface_StorageVersions_Call{Call: _e.mock.On("StorageVersions")}
}

func (_c *InternalV1alpha1Interface_StorageVersions_Call) Run(run func()) *InternalV1alpha1Interface_StorageVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InternalV1alpha1Interface_StorageVersions_Call) Return(_a0 v1alpha1.StorageVersionInterface) *InternalV1alpha1Interface_StorageVersions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InternalV1alpha1Interface_StorageVersions_Call) RunAndReturn(run func() v1alpha1.StorageVersionInterface) *InternalV1alpha1Interface_StorageVersions_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewInternalV1alpha1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewInternalV1alpha1Interface creates a new instance of InternalV1alpha1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInternalV1alpha1Interface(t mockConstructorTestingTNewInternalV1alpha1Interface) *InternalV1alpha1Interface {
	mock := &InternalV1alpha1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
