---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akash-operator-inventory
  labels:
    akash.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
      - nodes
      - events
      - services
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - patch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/proxy
    verbs:
      - get
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ceph.rook.io
    resources:
      - cephclusters
      - cephblockpools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventoryrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventories
    verbs:
      - create
      - patch
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akash-operator-inventory-hardware-discovery
  labels:
    akash.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-hardware-discovery
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
