apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - service_account.yaml
  - cluster_role.yaml
  - role-binding.yaml
