apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akash-services
resources:
  - service-accounts.yaml
  - cluster-roles.yaml
  - role-bindings.yaml
  - service.yaml
  - daemonset.yaml
  - deployment.yaml
configMapGenerator:
  - name: operator-inventory
    files:
      - config.yaml
