---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory-node
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-node
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
