name: codecov

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make modvendor
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .cache/tests/coverage.txt
