name: k8s-integration

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
   - cron: '* */12 * * *'

jobs:
  crd-e2e:
    env:
      KIND_NAME: kind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Prepare images
        run: make -s -C _run/kube kind-prepare-images
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v${{ env.KIND_VERSION }}"
          image: "kindest/node:${{ env.KINDEST_VERSION }}"
          config: ./_run/kube/kind-config.yaml
      - name: Docker Status
        run: docker ps -a
      - name: Setup Ingress K8S
        run: KUSTOMIZE_INSTALLS=akash-operator-inventory make -s -C _run/kube kind-cluster-setup-e2e-ci
      - name: k8s-ingress
        run: make -s -C _run/kube kind-k8s-ip
      - name: Kube Environment
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get pods,ingress,svc -A
      - name: Run E2E Tests
        run: make test-e2e-integration
      - name: Run K8s Tests
        run: make test-k8s-integration
      - name: Post-Run Kube Environment
        run: |
          kubectl get ns,pods,ingress,svc -A
